### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ghost** [Silvicek/cvar-rl-thesis#1]
Hi Silvicek,

  I am reading your thesis. At the APPENDIX A, you have one constraint: I_x' > yi C(x,yi) ...
where do you get it from?

    Thanks!

![image](https://user-images.githubusercontent.com/45894949/55696808-a3358d00-598c-11e9-87cb-2fc6b5d43ef7.png)

**Comment by Silvicek** [comment]
Hi cubicgate,
sorry for the late response. If you are asking about the form of this constraint, it is a common trick for formulating LPs for piecewise linear functions, see e.g. http://www.seas.ucla.edu/~vandenbe/ee236a/lectures/pwl.pdf page 4
I is the auxilary variable here.

If you meant something else, let me know!

**Comment by ghost** [comment]
Thanks @Silvicek for your help!
